'use strict';
const $=id=>document.getElementById(id);
const stateFields=['own_speed_kph','rival_speed_kph','gap_s','own_energy_mj','data_age_s','track_status'];
let scenarios=[],currentRequest=null,currentResult=null,lastEvaluatedRequest=null,replay=[],replayIndex=0,replayBelief=null,replayPolicy=null,apiKey='',busy=false,history=[];
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(v,d=2)=>Number.isFinite(v)?Number(v).toFixed(d):'—';
function error(message){$('error').textContent=message;$('error').hidden=!message;}
function toast(message){$('toast').textContent=message;$('toast').hidden=false;setTimeout(()=>$('toast').hidden=true,3500);}
async function api(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',...(apiKey?{'X-API-Key':apiKey}:{})},...(body?{body:JSON.stringify(body)}:{})});if(!r.ok){let message;try{const j=await r.json();message=typeof j.detail==='string'?j.detail:JSON.stringify(j.detail);}catch{message=await r.text();}throw Error(r.status===401?'API key required. Use the API key button to connect.':`Request failed (${r.status}): ${message}`);}return r.json();}
async function task(fn){if(busy)return;busy=true;error('');const controls=['evaluate','save','compare','replay-step','scenario','import-file','replay-reset'];controls.forEach(x=>$(x).disabled=true);try{await fn();}catch(e){error(e.message||String(e));}finally{busy=false;controls.forEach(x=>$(x).disabled=false);}}
function loadRequest(req){currentRequest=structuredClone(req);const s=req.state;$('own_energy_mj').max=req.policy?.capacity_mj??4;$('stage-unit').textContent=`${req.planning?.stage_s??4} seconds each`;stateFields.forEach(k=>$(k).value=s[k]??(k==='data_age_s'?0:'GREEN'));$('terminal_buffer_mj').value=req.planning?.terminal_buffer_mj??.25;const stages=req.planning?.stages??6;if(![...$('stages').options].some(o=>+o.value===stages))$('stages').add(new Option(`${stages} stages`,stages));$('stages').value=stages;replayBelief=null;}
function readRequest(){if(!$('state-form').reportValidity())throw Error('Check the highlighted input values.');const req=structuredClone(currentRequest||{state:{timestamp_s:1}});stateFields.forEach(k=>req.state[k]=k==='track_status'?$(k).value:Number($(k).value));req.planning={...req.planning,stages:Number($('stages').value),terminal_buffer_mj:Number($('terminal_buffer_mj').value)};if(currentRequest?.state){const old=currentRequest.state;if(req.state.own_speed_kph!==old.own_speed_kph||req.state.rival_speed_kph!==old.rival_speed_kph)req.state.speed_source='user_supplied';if(req.state.gap_s!==old.gap_s)req.state.gap_source='user_supplied';if(req.state.own_energy_mj!==old.own_energy_mj)req.state.energy_source='user_supplied';}delete req.belief;return req;}
function chart(target,series,{threshold=null,unit='',startX=0}={}){const el=$(target);if(!series.length||!series.some(s=>s.points.length)){el.innerHTML='<p>No forecast available for this state.</p>';return;}const W=700,H=245,L=48,R=18,T=18,B=32;const all=series.flatMap(s=>s.points);let lo=Math.min(...all.map(p=>p.y),threshold??Infinity),hi=Math.max(...all.map(p=>p.y),threshold??-Infinity);if(lo===hi){lo-=.5;hi+=.5;}const pad=(hi-lo)*.15;lo-=pad;hi+=pad;const xmax=Math.max(...all.map(p=>p.x),1);const x=v=>L+(v-startX)/(xmax-startX||1)*(W-L-R),y=v=>H-B-(v-lo)/(hi-lo)*(H-T-B);let svg=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="${esc(unit)} chart"><title>${esc(series.map(s=>s.name).join(', '))}; ${esc(unit)}</title>`;for(let i=0;i<=4;i++){let v=lo+(hi-lo)*i/4;svg+=`<line x1="${L}" x2="${W-R}" y1="${y(v)}" y2="${y(v)}" stroke="#dce1e5"/><text x="${L-9}" y="${y(v)+4}" text-anchor="end" fill="#66717b" font-size="12">${v.toFixed(1)}</text>`;}for(let i=0;i<=4;i++){let v=xmax*i/4;svg+=`<text x="${x(v)}" y="${H-8}" text-anchor="middle" fill="#66717b" font-size="12">${v.toFixed(0)}s</text>`;}if(threshold!==null)svg+=`<line x1="${L}" x2="${W-R}" y1="${y(threshold)}" y2="${y(threshold)}" stroke="#bd761d" stroke-dasharray="5 6"/>`;series.forEach(s=>{const path=s.points.map((p,i)=>`${i?'L':'M'}${x(p.x).toFixed(2)},${y(p.y).toFixed(2)}`).join(' ');svg+=`<path d="${path}" fill="none" stroke="${s.color}" stroke-width="2.5" ${s.dash?'stroke-dasharray="5 5"':''}/>`;});svg+='</svg>';el.innerHTML=svg;}
function render(result,req){currentResult=result;lastEvaluatedRequest=structuredClone(req);$('export').disabled=false;$('action').textContent=result.recommendation.replaceAll('_',' ');$('action').style.fontSize=result.status==='abstain'?'2rem':'';$('action').style.color=result.status==='abstain'?'#ffbf83':'';$('reason').textContent=result.reason;$('decision-status').textContent=result.status==='advisory'?'ENGINEER REVIEW':'ABSTAINED';$('horizon').textContent=`${result.horizon_s} SECOND HORIZON`;$('latency').textContent=`${fmt(result.latency_ms,1)} ms`;const p=req.policy||{};const required=(p.reserve_mj??.6)+(req.planning?.terminal_buffer_mj??.25);$('required').textContent=`${fmt(required)} MJ`;const best=result.candidates.find(c=>c.valid&&c.action===result.recommendation);$('finish').textContent=best?`${fmt(best.conservative_energy_mj)} MJ`:'—';$('sequence').innerHTML=best?best.trace.map(t=>`<div class="stage" data-action="${esc(t.action)}">${esc(t.action)}<span>+${t.time_s}s</span></div>`).join(''):'';
$('candidates').innerHTML=result.candidates.length?result.candidates.map(c=>`<tr class="${c.action===result.recommendation?'selected':''}"><td>${esc(c.action)}</td><td>${fmt(c.score_s,3)}</td><td>${fmt(c.conservative_energy_mj)}</td><td>${fmt(c.gap_s,3)}${c.valid?'s':''}</td><td class="${c.valid?'':'rejected'}">${c.valid?(c.action===result.recommendation?'Recommended':'Feasible'):esc(c.rejection_reasons.join('; '))}</td></tr>`).join(''):'<tr><td colspan="5">Input gate failed. Candidate forecasts were not generated.</td></tr>';
$('belief').innerHTML=['slow','neutral','fast'].map(k=>`<div class="belief-row"><span>${k[0].toUpperCase()+k.slice(1)}</span><div class="belief-bar"><div style="width:${result.belief[k]*100}%"></div></div><span>${(result.belief[k]*100).toFixed(0)}%</span></div>`).join('');
chart('energy-chart',best?[{name:'Expected energy',color:'#e4002b',points:[{x:0,y:req.state.own_energy_mj},...best.trace.map(t=>({x:t.time_s,y:t.energy_mj}))]},{name:'Conservative energy',color:'#526c8e',dash:true,points:[{x:0,y:Math.max(0,req.state.own_energy_mj-(req.state.energy_uncertainty_mj??.1))},...best.trace.map(t=>({x:t.time_s,y:t.conservative_energy_mj}))]}]:[],{threshold:required,unit:'Energy MJ'});
$('rules').innerHTML=[['Reserve',`${fmt(p.reserve_mj??.6)} MJ`],['Terminal requirement',`${fmt(required)} MJ`],['Deployment power cap',`${p.max_deploy_kw??120} kW`],['Window energy budget',`${fmt(req.planning?.deployment_budget_mj??2)} MJ`],['Maximum data age',`${p.max_data_age_s??5}s`],['Track status','GREEN required'],['Regulatory status','Unverified model policy']].map(([a,b])=>`<div class="rule"><span>${esc(a)}</span><strong>${esc(b)}</strong></div>`).join('');
const src=req.state.speed_source??'synthetic';document.querySelector('.source-tag').innerHTML=`${esc(src==='synthetic'?'SYNTHETIC SCENARIO':src.toUpperCase()+' INPUT')}<span>Energy: ${esc(req.state.energy_source??'simulated')} · Rules unverified</span>`;
}
async function evaluate(save=false,req=null){const input=req||readRequest();const r=await api(`/v2/plan?save=${save}`,input);render(r,input);if(save)toast(`Decision #${r.evaluation_id} saved with input and policy.`);return r;}
function setView(name){document.querySelectorAll('.view').forEach(v=>v.hidden=v.id!==name+'-view');document.querySelectorAll('.nav').forEach(b=>b.classList.toggle('active',b.dataset.view===name));const names={pit:['PIT WALL','Energy deployment','Compare the next action with the energy you will need later.'],lab:['SCENARIO LAB','Strategy comparison','A controlled comparison with shared starting conditions.'],evidence:['EVIDENCE & HISTORY','Decision evidence','Review the assumptions, constraints, and saved calculations.']};$('view-name').textContent=names[name][0];$('page-title').textContent=names[name][1];$('page-description').textContent=names[name][2];if(name==='evidence')task(loadHistory);}
async function loadHistory(){history=await api('/v2/history');$('history').innerHTML=history.length?history.map(h=>`<tr><td>#${h.id}</td><td>${esc(new Date(h.created).toLocaleString())}</td><td>${esc(h.output.recommendation)}</td><td>${fmt(h.input.state.own_energy_mj)} MJ</td><td>${fmt(h.output.latency_ms,1)} ms</td><td><button class="quiet" data-load="${h.id}">Inspect ↗</button></td></tr>`).join(''):'<tr><td colspan="6">No saved decisions yet. Use “Save decision” in the pit wall.</td></tr>';$('history').querySelectorAll('[data-load]').forEach(btn=>btn.onclick=()=>{const h=history.find(h=>h.id===+btn.dataset.load);loadRequest(h.input);render(h.output,h.input);$('scenario-description').textContent=`Saved evaluation #${h.id}`;setView('pit');});}
async function init(){await api('/health');$('connection').textContent='Backend connected';scenarios=await api('/v2/scenarios');$('scenario').innerHTML=scenarios.map(s=>`<option value="${esc(s.id)}">${esc(s.name)}</option>`).join('');replay=(await api('/v1/demo')).states;loadRequest(scenarios[0].request);$('scenario-description').textContent=scenarios[0].description+' Synthetic inputs.';await evaluate();}
$('evaluate').onclick=()=>task(()=>evaluate());$('save').onclick=()=>task(()=>evaluate(true));$('scenario').onchange=()=>task(async()=>{const s=scenarios.find(s=>s.id===$('scenario').value);loadRequest(s.request);$('scenario-description').textContent=s.description+' Synthetic inputs.';await evaluate();});
document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>setView(b.dataset.view));$('refresh-history').onclick=()=>task(loadHistory);
$('replay-step').onclick=()=>task(async()=>{if(replayIndex>=replay.length){toast('Replay finished. Reset to begin again.');return;}const req={state:replay[replayIndex],...(replayPolicy?{policy:replayPolicy}:{})};if(replayBelief)req.belief=replayBelief;loadRequest(req);const r=await evaluate(false,req);replayBelief=r.belief;replayIndex++;$('replay-progress').textContent=`${replayIndex} / ${replay.length} frames`;$('scenario-description').textContent=`Observation replay frame ${replayIndex}. Recommendations do not change the recorded future.`;});
$('replay-reset').onclick=()=>{replayIndex=0;replayBelief=null;$('replay-progress').textContent=`0 / ${replay.length} frames`;toast('Replay cursor and belief reset.');};
$('import-file').onchange=()=>task(async()=>{const f=$('import-file').files[0];if(!f)return;if(f.size>2*1024*1024)throw Error('Choose a JSON file smaller than 2 MB.');const data=JSON.parse(await f.text());let req=data.request||data;if(data.states){if(!Array.isArray(data.states)||!data.states.length||data.states.length>2000)throw Error('Replay must contain 1 to 2,000 states.');const valid=await api('/v1/replay',{states:data.states,...(data.policy?{policy:data.policy}:{})});replay=data.states;replayPolicy=data.policy||null;replayIndex=0;replayBelief=null;$('replay-progress').textContent=`0 / ${replay.length} imported frames`;req={state:replay[0],...(data.policy?{policy:data.policy}:{})};}if(!req.state)throw Error('Expected {state: ...}, {request: ...}, or {states: [...]} JSON.');const r=await api('/v2/plan',req);loadRequest(req);render(r,req);$('scenario-description').textContent=`Imported: ${f.name}. Source fields are caller declarations.`;toast('JSON validated and loaded.');});
$('export').onclick=()=>{if(!currentResult)return;const b=new Blob([JSON.stringify({request:lastEvaluatedRequest,result:currentResult},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='race-strategy-decision.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
$('compare').onclick=()=>task(async()=>{if(!$('seed').reportValidity())return;const req=readRequest();$('compare').textContent='Simulating…';try{const r=await api('/v2/compare',{request:req,seed:Number($('seed').value),ticks:15});const colors=['#e4002b','#526c8e','#bd761d'];$('comparison-results').innerHTML=r.results.map((v,i)=>`<article class="panel comparison-card" style="border-top:2px solid ${colors[i]}"><h3>${esc(v.controller)}</h3><strong>${fmt(v.final_energy_mj)} <small style="display:inline">MJ remaining</small></strong><p>Final gap proxy: ${fmt(v.final_gap_s,3)}s</p><small>${v.reserve_violations} reserve violations · ${v.switches} action switches</small></article>`).join('');for(const [id,key,unit] of [['compare-energy','energy_mj','Energy MJ'],['compare-gap','gap_s','Signed gap s']])chart(id,r.results.map((v,i)=>({name:v.controller,color:colors[i],points:v.trace.map(t=>({x:t.time_s,y:t[key]}))})),{unit,threshold:key==='energy_mj'?(req.policy?.reserve_mj??.6):null});$('comparison-note').textContent=`${r.duration_s}s simulated · Seed ${r.seed} · Computed in ${fmt(r.latency_ms,0)} ms. Red: planner; blue: reserve-aware HOLD; orange: greedy. ${r.scope}`;}finally{$('compare').textContent='Run comparison ↗';}});
$('key-button').onclick=()=>$('key-dialog').showModal();$('key-dialog').addEventListener('close',()=>{if($('key-dialog').returnValue==='apply'){apiKey=$('api-key').value;$('api-key').value='';task(init);}});
// An edited form must not leave an old result looking current.
$('state-form').addEventListener('input',()=>{$('decision-status').textContent='INPUT CHANGED · RE-EVALUATE';$('export').disabled=true;});
task(init);
